
export const BUG_NAME="NAME IS REQUIRED";
export const BUG_EMAIL="EMAIL IS REQUIRED";
export const BUG_PASS="PASSWORD IS REQUIRED";
export const BUG_PASS1="PASSWORD SHOULD CONTAIN ATLEAST ONE SPECIAL CHARACTER,ONE ALPHABETS ,ONE LOWERCASE ,ONE UPPERCASE ,ONE NUMBER AND MINIMUM OF LENGTH 8 ";
export const USERERROR="THE USER IS ALREADY REGISTERED";
export const ERRORMSG="THE USER IS NOT REGISTERED";
export const TASKERROR="TASK SHOULD BE EMPTY";
export const DESCERROR="DESCRIPTION SHOULD NOT BE EMPTY";
export const EMAILERROR="EMAIL MUST BE IN VALID FORMAT";
